create extension if not exists pgcrypto;

do $$ begin
  create type app_role as enum ('student','academic_maintainer','academic_coordinator','grievance_officer','content_editor','super_admin');
exception when duplicate_object then null; end $$;

do $$ begin
  create type welfare_type as enum ('scholarship','internship','fellowship','competitive_exam','part_time');
exception when duplicate_object then null; end $$;

do $$ begin
  create type academic_status as enum ('pending_review','approved','rejected','unpublished','archived');
exception when duplicate_object then null; end $$;

create table if not exists departments (id uuid primary key default gen_random_uuid(), name text not null unique, code text not null unique, active boolean default true);
create table if not exists profiles (id uuid primary key references auth.users(id) on delete cascade, full_name text not null default '', student_id text unique, email text, department_id uuid references departments(id), semester int, role app_role not null default 'student', status text not null default 'active', created_at timestamptz default now());
create table if not exists semesters (id uuid primary key default gen_random_uuid(), department_id uuid not null references departments(id) on delete cascade, semester_number int not null, name text not null, unique(department_id, semester_number));
create table if not exists subjects (id uuid primary key default gen_random_uuid(), department_id uuid not null references departments(id) on delete cascade, semester_id uuid not null references semesters(id) on delete cascade, name text not null, code text);
create table if not exists events (id uuid primary key default gen_random_uuid(), title text not null, description text default '', start_at timestamptz not null, end_at timestamptz, venue text, poster_url text, status text default 'draft', created_by uuid references profiles(id));
create table if not exists event_registrations (id uuid primary key default gen_random_uuid(), event_id uuid not null references events(id) on delete cascade, student_id uuid not null references profiles(id) on delete cascade, registered_at timestamptz default now(), unique(event_id, student_id));
create table if not exists announcements (id uuid primary key default gen_random_uuid(), title text not null, body text not null, category text, priority text default 'normal', publish_at timestamptz, expires_at timestamptz, status text default 'draft', created_by uuid references profiles(id));
create table if not exists grievances (id uuid primary key default gen_random_uuid(), student_id uuid not null references profiles(id), category text not null, title text not null, description text not null, status text default 'submitted', assigned_to uuid references profiles(id), created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists grievance_updates (id uuid primary key default gen_random_uuid(), grievance_id uuid not null references grievances(id) on delete cascade, author_id uuid not null references profiles(id), message text default '', old_status text, new_status text, created_at timestamptz default now());
create table if not exists blood_donors (id uuid primary key default gen_random_uuid(), student_id uuid not null unique references profiles(id) on delete cascade, blood_group text not null, available boolean default true, consented_at timestamptz default now());
create table if not exists blood_requests (id uuid primary key default gen_random_uuid(), requester_id uuid not null references profiles(id), blood_group text not null, units numeric, urgency text default 'open', location text, required_by timestamptz, status text default 'open', created_at timestamptz default now());
create table if not exists welfare_items (id uuid primary key default gen_random_uuid(), type welfare_type not null, title text not null, organization text not null, description text default '', eligibility text, mode text, location text, deadline timestamptz, source_url text, attachment_url text, status text default 'draft', created_by uuid references profiles(id));
create table if not exists magazine_issues (id uuid primary key default gen_random_uuid(), title text not null, edition text, cover_url text, description text, published_at timestamptz, status text default 'draft', created_by uuid references profiles(id));
create table if not exists magazine_articles (id uuid primary key default gen_random_uuid(), issue_id uuid not null references magazine_issues(id) on delete cascade, title text not null, author_name text, body text default '', media_url text, status text default 'draft');
create table if not exists map_locations (id uuid primary key default gen_random_uuid(), name text not null, category text not null, description text, latitude numeric, longitude numeric, map_x numeric, map_y numeric, contact text, status text default 'active');
create table if not exists emergency_contacts (id uuid primary key default gen_random_uuid(), category text not null, name text not null, phone text not null, secondary_phone text, instructions text, verified_at timestamptz, active boolean default true);
create table if not exists notifications (id uuid primary key default gen_random_uuid(), user_id uuid not null references profiles(id) on delete cascade, type text not null, title text not null, body text not null, read_at timestamptz, created_at timestamptz default now());
create table if not exists notification_preferences (user_id uuid primary key references profiles(id) on delete cascade, announcements boolean default true, events boolean default true, grievances boolean default true, welfare boolean default true, academics boolean default true, magazine boolean default true, emergency boolean default true);
create table if not exists device_tokens (id uuid primary key default gen_random_uuid(), user_id uuid not null references profiles(id) on delete cascade, token text not null unique, platform text, active boolean default true, last_seen_at timestamptz default now());
create table if not exists academic_materials (id uuid primary key default gen_random_uuid(), title text not null, description text, department_id uuid not null references departments(id), semester_id uuid not null references semesters(id), subject_id uuid not null references subjects(id), material_type text not null, academic_year text, storage_path text not null, original_filename text not null, mime_type text not null, file_size bigint not null, content_hash text, uploaded_by uuid not null references profiles(id), status academic_status not null default 'pending_review', rejection_reason text, approved_by uuid references profiles(id), approved_at timestamptz, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists academic_reports (id uuid primary key default gen_random_uuid(), material_id uuid not null references academic_materials(id) on delete cascade, reported_by uuid not null references profiles(id), reason text not null, description text, status text default 'open', reviewed_by uuid references profiles(id), reviewed_at timestamptz, created_at timestamptz default now());
create table if not exists academic_maintainers (id uuid primary key default gen_random_uuid(), user_id uuid not null references profiles(id) on delete cascade, department_id uuid not null references departments(id) on delete cascade, semester_id uuid references semesters(id) on delete cascade, subject_id uuid references subjects(id) on delete cascade, active boolean default true, assigned_at timestamptz default now());
create table if not exists academic_moderation_logs (id uuid primary key default gen_random_uuid(), material_id uuid not null references academic_materials(id) on delete cascade, actor_id uuid not null references profiles(id), action text not null, old_status academic_status, new_status academic_status, reason text, created_at timestamptz default now());
create table if not exists audit_logs (id uuid primary key default gen_random_uuid(), actor_id uuid references profiles(id), action text not null, entity_type text not null, entity_id uuid, metadata jsonb default '{}'::jsonb, created_at timestamptz default now());
create index if not exists idx_academic_lookup on academic_materials(department_id, semester_id, subject_id, status);
create index if not exists idx_welfare_lookup on welfare_items(type,status,deadline);
create index if not exists idx_notifications_user on notifications(user_id,created_at desc);
